name: Run tttiiibot

on:
  workflow_dispatch:

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      - name: تحميل الملفات
        uses: actions/checkout@v4

      - name: إعداد Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: تثبيت المكتبات
        run: pip install -r requirements.txt

      - name: إنشاء ملف إعداد الدخول
        run: |
          echo "usernames['wikipedia']['ar'] = 'TttiiiBot@TttiiiBot'" > user-config.py
          echo "authenticate['en.wikipedia.org'] = ('TttiiiBot@TttiiiBot', '${{ secrets.WIKI_PASSWORD }}')" >> user-config.py

      - name: تشغيل البوت
        run: python bot.py
